# Generated by Django 3.0.6 on 2022-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEKJOBSPLATFORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_resume',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
