# Generated by Django 3.0.6 on 2022-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEKJOBSPLATFORM', '0002_auto_20220331_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_education_extracted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_experience_extracted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_skills_extracted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seeker_resume',
            name='job_education_extracted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seeker_resume',
            name='job_experience_extracted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seeker_resume',
            name='job_skills_extracted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
